### ISSUE TITLE
dataset availability

### ISSUE THREAD

**Issue by lwaldron** [elmoen/clustered_data_code#1]
Would you link to the dataset in README.md file? I haven't been able to find it. If it's less than 10MB in .zip format, you could post it to this issue. Thanks for the useful teaching paper!

**Comment by elmoen** [comment]
Thanks for bringing this up - the dataset is now available (PtenAnalysisData.csv)

**Comment by lwaldron** [comment]
Thank you @elmoen! Much appreciated.
